# Generated by Django 4.0.1 on 2023-02-24 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='VC Id')),
                ('emi_type', models.CharField(choices=[('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default='M', max_length=12, verbose_name='EMI Type')),
                ('total_amount', models.PositiveBigIntegerField(verbose_name='Total Amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('organizer', models.ManyToManyField(related_name='vc_organizer_users', to=settings.AUTH_USER_MODEL, verbose_name='Organizers')),
                ('participant', models.ManyToManyField(blank=True, null=True, related_name='vc_participant_users', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'VC',
                'verbose_name_plural': 'VCs',
            },
        ),
        migrations.CreateModel(
            name='AmountReceivedByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount Received')),
                ('received_on', models.DateTimeField(auto_now_add=True, verbose_name='Received On')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receive_users', to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
                ('vc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vc_amount_receivers', to='vc.vc', verbose_name='VC')),
            ],
            options={
                'verbose_name': 'Amount Received By User',
                'verbose_name_plural': 'Amount Received By Users',
            },
        ),
        migrations.CreateModel(
            name='AmountPaidByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount Paid')),
                ('paid_on', models.DateTimeField(auto_now_add=True, verbose_name='Paid On')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pay_users', to=settings.AUTH_USER_MODEL, verbose_name='Paid By')),
                ('vc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vc_amount_payers', to='vc.vc', verbose_name='VC')),
            ],
            options={
                'verbose_name': 'Amount Paid By User',
                'verbose_name_plural': 'Amount Paid By Users',
            },
        ),
    ]
