# Generated by Django 4.0.1 on 2023-02-24 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vc',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vc',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='vc_participant_users', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
