# Generated by Django 4.0.1 on 2023-03-04 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vc', '0003_remove_vc_total_amount_vc_emi_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vcs', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
