# Generated by Django 4.0.1 on 2023-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0004_vc_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vc',
            name='is_active',
        ),
        migrations.AddField(
            model_name='vc',
            name='interest',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Interest'),
        ),
        migrations.AddField(
            model_name='vc',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('OG', 'On-Going'), ('CP', 'Completed'), ('TM', 'Terminated')], default='CR', max_length=2, verbose_name='Status'),
        ),
    ]
